### ISSUE TITLE
Suggestions for HTML report

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#76] opened 2015-03-09 16:49 UTC
I am testing BDS for my tf chipseq pipeline. BDS is awesome. It worked perfectly for my project! dep() is still buggy but task() with if (OUT<-IN) was enough for me to deal with intermediate files. The following is the HTML report for single end data set.

http://amold.lbl.gov/bds/SE2/tf_chipseq.bds.20150309_020725_181.report.html

There are several suggestions:

1) How can I specify the name of each task? Line number is not enough for a good report. Currently ID and name in the task details section are always the same. Is it possible to specify each task's color too?

ID 	task.modules_tf_chipseq.line_321.id_1
Name 	task.modules_tf_chipseq.line_321.id_1

2) In the timeline section, can I have task duration at the end of the progress bar for each task? It would be also good to have time ticks both on top and at the bottom of the timeline.

3) Task graph is so messy I don't actually understand what is plotted there.

**Comment by pcingola** [comment] 2015-03-11 11:50
Hi,
  Thank you for your feedback!
Can you send an example of a "buggy" dep()? I'll do my best to fix it.

Answering your questions:

  1) You can specify a task name using 'taskName':

     task( taskName := 'my task name' ) ...

  2) Timeline is based on Google's charts API, I'm not sure if adding that information is possible, I'll take a look at it (if you know how to do it, please let me know).

  3) Yes, I agree. Either cytoscape.js (http://js.cytoscape.org/) is not handling it as I expected or I'm doing a terrible job at specifying how tasks are shown. I have to try something else because now is almost useless. Again, any tips on how to improve this are more than welcomed (I never used cytoscape.js before).

**Comment by leepc12** [comment] 2015-03-11 21:53
Thanks for your response!

I am trying to reproduce the dep bug in a simple code but bds works perfectly with the simple code...

My project code (with buggy dep) has a similar structure with the simple code. I put debug line (print( ("2.out2" <- "2.in" ) + "\n") // TEST) for many locations of the code and some of them were TRUE and others FALSE, which should not happen. After I replaced all dep() { } with if and task() { }, all of debug line gave me FALSE.

Sorry I cannot reproduce the bug with the simple code but I am sure that it exists.

////////////// simple code
#!/usr/bin/env bds

print( ("2.out2" <- "2.in" ) + "\n") // TEST

for (int i=1; i<=2; i++) {
    print( ("2.out2" <- "2.in" ) + "\n") // TEST
    for (int j=1; j<=2; j++) {
        par fnc1( i, j )
        print( ("2.out2" <- "2.in" ) + "\n") // TEST
    }
}
print( ("2.out2" <- "2.in" ) + "\n") // TEST

exit(0)


void fnc1( int i, int j ) {

    if ( j==1 ) {
        IN  := "$i.in"
        TMP := "TMP1"
        OUT := "$i.out1"

        dep( TMP <- IN ) {
            sys echo IN-TMP, j=1
            sys cat $IN > $TMP
        }
        dep( OUT <- TMP ) {
            sys echo TMP-OUT, j=1
            sys cat $TMP > $OUT
        }

        goal OUT
    }
    else {
        IN  := "$i.in"
        TMP := "TMP2"
        OUT := "$i.out2"

        dep( TMP <- IN ) {
            sys echo IN-TMP, j=2
            sys cat $IN > $TMP
        }
        dep( OUT <- TMP ) {
            sys echo TMP-OUT, j=2
            sys cat $TMP > $OUT
        }

        goal OUT
    }

}

**Comment by pcingola** [comment] 2015-03-13 20:25
OK, I'll take a look at the code and see if I can find something, but 
trying to find a bug without an example is going to be hard...

**Comment by pcingola** [comment] 2015-04-03 14:01
Could not reproduce error conditions. 
I'm closing it, but please let me know if you find this issue again.

**Closed by pcingola** 2015-04-03 14:01 UTC
