### ISSUE TITLE
Clarification of escaping characters in sys commands

### ISSUE THREAD

**Issue by kmhernan** [pcingola/BigDataScript#63] opened 2015-01-24 15:19 UTC
Hello,

I have had no success using things like `awk` or even trying to write the `-R` readgroup parameter for `bwa`. I see that you have the same problem and simply `grep -v ^@PG`. There has to be a better way to deal with this. It really makes it impossible to use `awk` and I find that I have to create silly bash scripts containing the `awk` command I want to use.

For example, I want to run something like this:

```
bedtools intersect -a fileA.bed -b fileB.bed -wa -wb | awk '{print $1 "\t" $2 "\t" $3 "\n" $4 "\t" $5 "\t" $6}' | sort -k1,1 -k2,2n > intersects.bed
```

But it will NOT work in BDS. It does not like the `\n`. In BDS I have added `\` and the tabs seem ok, but the `\n` throws exception. I basically have to write that silly one line `awk` to a bash script and use that script in BDS to work. Suggestions?

**Comment by pcingola** [comment] 2015-01-24 21:31
Seems to work for me:

    # Input  file
    $ cat z.txt
    @AA AAAAAAA
    @PG Hello
    @ZZ ZZZZZZZ

    # Script
    $ cat z.bds
    #!/usr/bin/env bds

    task cat z.txt | grep -v ^@PG

    # Run script, get expected results:
    $ ./z.bds
    @AA AAAAAAA
    @ZZ ZZZZZZZ

So the 'grep -v ^@PG' seems to work OK.
Can you send a minimal script shows the error?

**Comment by kmhernan** [comment] 2015-01-24 22:54
Sorry, I was unclear. The `grep` works. So here is one of the examples in `/include`:

```
task( bam <- [fq1, fq2] , cpus := cpusMapping ) sys bwa mem -R '$readGroupString' -t $cpusMapping $referenceFasta $fq1 $fq2 | grep -v "^@PG" | samtools view -S -q $minMapQ -u - | samtools sort -@ $cpus -m $mapSortMemory - $bamBase
```

The `$readGroupString` literally prints a tab, when we really want it to be escaped and samtools will complain about the `@PG` line. This is why you have to `grep -v` it. When you want to actually use `\n` in some `sys` command it does not work and I can not escape it! Does that make more sense??

**Comment by pcingola** [comment] 2015-01-25 17:14
OK, I get it now. I've actually shoot myself in the foot several times lately with 
this double layer of escaping. I removed escaping from sys and task to make 
it more transparent.

Here is a sample script:

    #!/usr/bin/env bds

    hi := "Hello"
    println   'print_quote        |\t|'
    println   'print_quote        |\t|    variable:$hi'

    println   "print_double       |\t|"
    println   "print_double       |\t|    variable:$hi"

    println   "print_double_esc   |\\t|"
    println   "print_double_esc   |\\t|   variable:$hi"

    # These lines depend on the shell being used
    # Using /bin/sh I see a 'tab' character, whereas 
    # using /bin/bash I see a '\t' (escaped tab)
    sys  echo "sys                |\t|"
    sys  echo "sys                |\t|    variable:$hi"

    task echo "task               |\t|"
    wait
    task echo "task               |\t|    variable:$hi"

When you run it, you get

    print_quote        |\t|
    print_quote        |\t|    variable:$hi
    print_double       |    |
    print_double       |    |    variable:Hello
    print_double_esc   |\t|
    print_double_esc   |\t|   variable:Hello
    sys                |\t|
    sys                |\t|    variable:Hello
    task               |\t|
    task               |\t|    variable:Hello

What do you think? It should be much easier now...

**Comment by kmhernan** [comment] 2015-01-26 15:47
I think that makes sense. I'm sure you are familiar with it, but the implementation of the `CommandLineFunction` trait in `Queue` is rather elegant. When you don't want to use any of their API's to write a command, you do have to escape:

```
def commandLine = "cat %s | grep -v \"#\" > %s".format(files, out)
```

Or, you can use their API:

```
override def commandLine = super.commandLine +
                           required("eff") +
                           conditional(verbose, "-v") +
                           optional("-c", config) +
                           required("-i", "vcf") +
                           required("-o", "vcf") +
                           required(genomeVersion) +
                           required(inVcf) +
                           required(">", escape=false) +  // This will be shell-interpreted as an output redirection
                           required(outVcf)
```

However, the API approach would probably take quite a bit of reworking of the entire `sys` implementation. So, I am okay with the direct escaping approach as long as the finalized implementation is documented in the language syntax page! I will need to check how this build handles the `\n`.

Kyle

**Comment by pcingola** [comment] 2015-01-26 16:22
So, they just use String.format()
I think I'd rather go for the direct approach and not having to escape anything.

What do you mean by "...build handles the \n"? Can you give me an example of what the problem is?

**Comment by kmhernan** [comment] 2015-01-26 16:30
Yup String.format() it is for Queue... I like the direct without escaping.... 

Sure, here is a case (I am NOT using the version with the newest commits v0.999d):

```
sys echo -e "Hello\tWorld" | awk '{print $1 "\n" $2}'
```

Would throw this exception:
```
awk: {print $1 "
awk:           ^ unterminated string
Fatal error: test.bds, line 1, pos 1. Exec failed.
	Exit value : 1
	Command    :  echo -e "Hello	World" | awk '{print $1 "
" $2}'

Creating checkpoint file 'test.bds.line_1.chp'
```

Trying to escape `\n` doesn't seem to work either!

**Comment by pcingola** [comment] 2015-01-26 19:03
Looks like it works OK now:

    $ cat z.bds
    sys echo -e "Hello\tWorld" | awk '{print $1 "\n" $2}'
 
    $ bds z.bds
    Hello
    World
 
    $ bds -version
    BigDataScript 0.999d (build 2015-01-26), by Pablo Cingolani

**Comment by kmhernan** [comment] 2015-01-27 18:48
Ok, so I am now having a problem with environmental variables after this change. I need to read the env variable from a config file, but the env variable won't be set until the module is loaded within the task. Before this change, I could have something like:
```
string picardExe = "\$PICARD"
task {
  sys . /etc/profile.d/modules.sh; module load java/1.7.0; module load picard/1.123
  sys java -jar $picardExe/VcfFormatConverter.jar
}
```

and it would work, but now it does not work. I can't figure out how to read an environmental variable ID into a string before it is actually set in the environment. Does that make sense??

Kyle

**Comment by kmhernan** [comment] 2015-01-27 20:00
OK OK... so It appears to work when you have `string picardExe = "\${PICARD}"`. Adding in the brackets worked on my test case file. However, when you are reading from a config file, it is different.

This is what works for reading an environmental variable name from an config file:

```
# PICARD SETTINGS
picard_modname = picard/1.123
picard_exe = ${PICARD}
picard_merge_alignments_mem = 4
picard_dedup_mem = 4
picard_metrics_mem = 4
picard_vcf_mem = 4
```

There is no `\` in the config file, if you do add it, the `sys` command will interpret it as a raw string/literal `${PICARD}` ...

**Comment by pcingola** [comment] 2015-01-27 23:50
I'm puzzled.. is this a problem or a feature?  :-) 
  The method config("file.txt"), reads strings as literals (no escaping needed). When 
you read "picard_exe = ${PICARD}" you get exactly the same string (no backslash 
required), which your sys commands passes (again no escaping needed).
  So, in my opinion, this is the correct behaviour (plus it simplifies your life by not requiring 3 different levels of escaping). Please, let me know if you disagree.

**Comment by kmhernan** [comment] 2015-01-28 00:26
So in previous versions if I didn't backslash the environmental variable in the config file it would not be read correctly to the string I assigned it to (it would automatically try to convert the variable in the config file to its assigned value). After updating to the changes you made with the backslashing of `sys` commands that changed. As it stands now makes sense and is good in my opinion!

**Comment by pcingola** [comment] 2015-01-28 00:32
Great, I'll close this bug then.

**Closed by pcingola** 2015-01-28 00:32 UTC
